### ISSUE TITLE
Feature Request: Howler escape hatch

### ISSUE THREAD

**Issue by nquinlan** [joshwcomeau/use-sound#35]
I've implemented use-sound in a recent project and been really happy with how easy the library has made it.

However, for this project, I need to get Howler's audio context (`Howler.ctx`), but right now the library doesn't ever expose its instance of Howler. 

**I'm wondering if you'd support a PR to add an escape hatch for Howler proper?** If so, do you have a way you'd prefer to see it done, as I'm fairly new to the React ecosystem, and don't know the most React-ey way to go about exposing it in a hook.

Thanks for a great project!

**Comment by joshwcomeau** [comment]
Hm, so it exposes the `Howl` instance, under [`exposedData`](https://github.com/joshwcomeau/use-sound#exposeddata). But I do seem to remember there being a Howler as well.

Yeah, I'd support a PR that exposes it in the same way (maybe it could be keyed under Howler, in that same object?)

I know it's been a while, I hope you were able to find a solution! As a reminder for anyone reading this, I've outlined my commitments to this project in [CONTRIBUTING.md](https://github.com/joshwcomeau/use-sound/blob/master/CONTRIBUTING.md) — the short version is I encourage folks to fork the project and make whatever changes they'd like, since I can't guarantee timely action in this project 😅
