### ISSUE TITLE
Make Howler a peer dependency.

### ISSUE THREAD

**Issue by ivands** [joshwcomeau/use-sound#47]
Can we make Howler a peer dependency?
So people can upgrade to the latest howler without the need for you to upgrade the version every time.

**Comment by joshwcomeau** [comment]
Hm, so I imagine people could use Yarn resolutions if they needed to do that, right? I presume there's an NPM alternative now as well.

I like the idea of keeping it as a dependency because I'd rather keep the "happy path" simple. Since I don't imagine most folks will care about Howler versions, I don't mind if that path is a bit more complicated (though I do want to make sure it's possible!)

**Comment by n1ru4l** [comment]
npm will now install peerDependencies by default.

**Comment by 0xdevalias** [comment]
> I like the idea of keeping it as a dependency because I'd rather keep the "happy path" simple.

Wouldn't 'keeping the happy path simple' just involve telling people to install both as part of the 'getting started' docs though? I feel like this is a pretty common case for frontend web-dev, so shouldn't be too much of a burden for users, while making this hook far more useful for power-users.

**Comment by joshwcomeau** [comment]
I don't have the bandwidth to think about this. Forks encouraged.
