### ISSUE TITLE
How to use with Next.js?

### ISSUE THREAD

**Issue by abcd-ca** [joshwcomeau/use-sound#56]
Hi, l'm trying to use this in TypeScript with Next.js. I'm getting,

> TS2307: Cannot find module '../../../public/sfx/correct-answer/test.mp3' or its corresponding type declarations.

I know my path is right. I don't know if I can get a webpack file-loader configured but even if I did, would I still get this TypeScript error? 

Your library looks really cool and I'd like to use it so would appreciate any help. I couldn't find much by searching the web.

**Comment by joshwcomeau** [comment]
Hey there — Pretty sure your path should be `/sfx/correct-answer/test.mp3`. In Next.js, all static assets in `/public/` can be accessed from `/` (so `/public/images/cat.jpg` would be `/images/cat.jpg`).

Hope it helps!

**Comment by iwgx** [comment]
I'm also encounter this problem, although my import has been correct.

This is how I fix it.
I still don't know why we can't use `import`.

![Screenshot 2021-02-11 152938](https://user-images.githubusercontent.com/20817629/107615037-0c1f7780-6c7e-11eb-80f8-fd10410473a3.png)

**Comment by DianaKoenraadt** [comment]
Same problem. I've added the `url-loader` and `file-loader` packages, to no avail. The browser shouts 404 at me in the Chrome Developer Tools console and I'm not even calling the paly function yet. Does anyone have a full example with nextjs so that I know where people are placing their sound files on disk?

**Comment by iwgx** [comment]
@DianaKoenraadt I'm using it in my project https://github.com/iwgx/morsible

**Comment by DianaKoenraadt** [comment]
Apparently you omit the `/public` part when you use it. So if you put the mp3 in `/public/sounds/my-sound.mp3`, you reference it 

`const [play] = useSound('/sounds/my-sound.mp3');`

**Comment by joshwcomeau** [comment]
Ah, sorry for the confusion — Silly mistake on my part, especially since I
use Nextjs myself!

I've removed the example from the README, since yeah really I want to
encourage people to consult the docs for their own framework rather than
provide instructions for it (that are subject to grow stale as frameworks
evolve)
