### ISSUE TITLE
IDM download sound

### ISSUE THREAD

**Issue by sm2017** [joshwcomeau/use-sound#65]
This is your sample code , If we have installed Internet Download Manager (IDM) in our machine, it display download dialog when `useSound` executed, How we can prevent it?

```js
import useSound from 'use-sound';

import boopSfx from '../../sounds/boop.mp3';

const BoopButton = () => {
  const [play] = useSound(boopSfx);

  return <button onClick={play}>Boop!</button>;
};
```

**Comment by sm2017** [comment]
@joshwcomeau I am wondering that why the IDM won't display dialog on the https://use-sound.netlify.app/?path=/story/usesound--simple

**Comment by lewiji** [comment]
I've not used IDM, btw, but from some research online it looks like the standard advice is simply to configure IDM on the client side not to start downloading sounds either by filetype or domain. After all this is what IDM is programmed to do, and is expected behaviour for it.

Unfortunately the use-sound storybook link seems to be broken right now, so I can't verify the below but I had a couple of ideas of why it may not trigger a download there:

* maybe the example is embedded in an iframe and IDM doesn't have permission to inspect it?
* maybe they are using a different mimetype or file extension when building and serving on netlify by default which "fools" idm?

I suspect the first idea, maybe you could try a simple experiment of embedding your app code into an iframe in a parent page.

**Comment by joshwcomeau** [comment]
Sorry, I don't know anything about IDM
