### ISSUE TITLE
Move to a community supported organisation so others can contribute?

### ISSUE THREAD

**Issue by 0xdevalias** [joshwcomeau/use-sound#80]
I noticed your recent comments that you don’t have the bandwidth to actively support this project, and encouraged forks. While I totally understand that, I wonder if it could fragment the ecosystem, and whether it might be a better solution to move the project to a GitHub organisation and allow others to help contribute/maintain it.

**Comment by joshwcomeau** [comment]
It's an interesting idea, but it's not really the right fit for my situation.

This package is a package I created for my own purposes, and I thought I'd share it in case others found it useful. I still sorta see it as my own personal project though, and I like it that way. With [Guppy](https://github.com/joshwcomeau/guppy), I really wanted it to be a community effort, and I discovered pretty quickly that it was burning me out, since I was spending all my free time managing the project. I'm eager not to fall into the same trap 😅

I do realize that this is kind of a selfish way to think about it, but ultimately, this project is really pretty small — all the hard work is delegated to Howler. So there really aren't as many downsides when it comes to forking, or even just creating your own hook using this one as inspiration.  

That said, most of the time when I suggest someone makes a fork, it's because they want to extend it with functionality for their own usecase, and regardless of whether this project moves to an org or not, I'd want to keep giving that advice; I've seen too many projects try to satisfy every usecase, and wind up bloated and buggy as a result. This package really isn't meant to be a comprehensive React audio tool, it's meant to be a hook you can quickly add to trigger a sound effect when the user interacts with something. 

So there's actually a sort of benefit to me being so time-restricted; it makes me prioritize feature requests pretty ruthlessly, and ultimately that creates a better library for the 80% of users who don't have specific requirements beyond that basic functionality. And I have the bandwidth to support them, and to keep this library up-to-date, stuff like that. I just don't have the bandwidth to treat this like a constantly-evolving library, and I suspect the tool might be better because of it.

Hope that makes sense! Appreciate the comment.

**Comment by 0xdevalias** [comment]
*nods* I can totally understand that. Thanks for the detailed response.
